### ISSUE TITLE
Error: Type mismatch in argument 'ctx' at (1); passed INTEGER(8) to INTEGER(4)

### ISSUE THREAD

**Issue by barracuda156** [interkosmos/fortran-lua53#6]
```
 <INFO> LINKER OPTIONS:   -L/opt/local/lib -llua.5.3
 <INFO> INCLUDE DIRECTORIES:  []
 + mkdir -p build/gfortran_EDF3F128DBFCA123
[  0%]                        lua.f90
 + mkdir -p build/gfortran_EDF3F128DBFCA123/fortran-lua53/
 + gfortran -c ././src/lua.f90  -O3 -funroll-loops -Wimplicit-interface -fPIC -fmax-errors=1 -fcoarray=single -J build/gfortran_EDF3F128DBFCA123 -Ibuild/gfortran_EDF3F128DBFCA123 -o build/gfortran_EDF3F128DBFCA123/fortran-lua53/src_lua.f90.o
././src/lua.f90:921:74:

  921 |         call lua_callk(l, nargs, nresults, int(0, kind=i8), c_null_funptr)
      |                                                                          1
Error: Type mismatch in argument 'ctx' at (1); passed INTEGER(8) to INTEGER(4)
compilation terminated due to -fmax-errors=1.
[ 50%]                        lua.f90  done.

././src/lua.f90:921:74:

  921 |         call lua_callk(l, nargs, nresults, int(0, kind=i8), c_null_funptr)
      |                                                                          1
Error: Type mismatch in argument 'ctx' at (1); passed INTEGER(8) to INTEGER(4)
compilation terminated due to -fmax-errors=1.
<ERROR> Compilation failed for object " src_lua.f90.o "
<ERROR>stopping due to failed compilation
STOP 1
```

**Comment by barracuda156** [comment]
This is on powerpc (32-bit).

**Comment by interkosmos** [comment]
Should be fixed. Thanks for reporting!

**Comment by barracuda156** [comment]
@interkosmos Sorry, still fails for me:
```
--->  Building fortran-lua53
xinstall: mkdir /opt/local/var/macports/build/_opt_PPCRosettaPorts_fortran_fortran-lua53/fortran-lua53/work/bin
Executing:  cd "/opt/local/var/macports/build/_opt_PPCRosettaPorts_fortran_fortran-lua53/fortran-lua53/work/fortran-lua53-976f0e9513e236b0225138a7a8978f4ddcbfa20f" && /opt/local/bin/fpm install --verbose --prefix="/opt/local/var/macports/build/_opt_PPCRosettaPorts_fortran_fortran-lua53/fortran-lua53/work/opt/local" --profile="release" --link-flag="-L/opt/local/lib -llua.5.3" 
 + mkdir -p build/dependencies
 <INFO> BUILD_NAME: build/gfortran
 <INFO> COMPILER:  gfortran
 <INFO> C COMPILER:  gcc
 <INFO> CXX COMPILER: g++
 <INFO> COMPILER OPTIONS:   -O3 -funroll-loops -Wimplicit-interface -fPIC -fmax-errors=1 -fcoarray=single
 <INFO> C COMPILER OPTIONS:  
 <INFO> CXX COMPILER OPTIONS: 
 <INFO> LINKER OPTIONS:   -L/opt/local/lib -llua.5.3
 <INFO> INCLUDE DIRECTORIES:  []
 + mkdir -p build/gfortran_EDF3F128DBFCA123
[  0%]                        lua.f90
 + mkdir -p build/gfortran_EDF3F128DBFCA123/fortran-lua53/
 + gfortran -c ././src/lua.f90  -O3 -funroll-loops -Wimplicit-interface -fPIC -fmax-errors=1 -fcoarray=single -J build/gfortran_EDF3F128DBFCA123 -Ibuild/gfortran_EDF3F128DBFCA123 -o build/gfortran_EDF3F128DBFCA123/fortran-lua53/src_lua.f90.o
././src/lua.f90:921:74:

  921 |         call lua_callk(l, nargs, nresults, int(0, kind=i8), c_null_funptr)
      |                                                                          1
Error: Type mismatch in argument 'ctx' at (1); passed INTEGER(8) to INTEGER(4)
[ 50%]                        lua.f90  done.

././src/lua.f90:921:74:

  921 |         call lua_callk(l, nargs, nresults, int(0, kind=i8), c_null_funptr)
      |                                                                          1
Error: Type mismatch in argument 'ctx' at (1); passed INTEGER(8) to INTEGER(4)
<ERROR> Compilation failed for object " src_lua.f90.o "
<ERROR>stopping due to failed compilation
STOP 1
Command failed:  cd "/opt/local/var/macports/build/_opt_PPCRosettaPorts_fortran_fortran-lua53/fortran-lua53/work/fortran-lua53-976f0e9513e236b0225138a7a8978f4ddcbfa20f" && /opt/local/bin/fpm install --verbose --prefix="/opt/local/var/macports/build/_opt_PPCRosettaPorts_fortran_fortran-lua53/fortran-lua53/work/opt/local" --profile="release" --link-flag="-L/opt/local/lib -llua.5.3" 
Exit code: 1
```
From commit 976f0e9513e236b0225138a7a8978f4ddcbfa20f

**Comment by interkosmos** [comment]
Should be really fixed now, tried it on a virtualised 32-bit system.

**Comment by barracuda156** [comment]
@interkosmos Thank you very much, I will try it soon.

**Comment by barracuda156** [comment]
Yes, works now, thank you!
